# apitesteille tiedosto

POST http://localhost:5000/api/user/login
content-type: application/json
{
	"username": "testuser",
	"password": "test"
}

###

GET http://localhost:5000/api/user/myinformation
Accept: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1laWRlbnRpZmllciI6IjY3ZjhlYzJmMDE2MzA0ZTJiOTNjOGY2MyIsImV4cCI6MTc0NDkyNTk4NywiaXNzIjoiQnVkZ2V0YXBwIiwiYXVkIjoiQnVkZ2V0YXBwVXNlcnMifQ.SbUogc_4tKX6poIbh8plb-9SHtQ-NT0GZ2Pj8HswomI
###

POST http://localhost:5000/api/user/new
content-type: application/json
{
	"Username": "testuser",
	"Firstname": "test",
	"Lastname": "user",
	"Password": "test",
	"Salary": 3500,
	"HousingAllowance": 1000,
	"StudyAllowance": 300,
	"OtherIncome": [50],
	"Rent": 800.10,
	"Mortage": 110.50,
	"ElectricityBill": 100,
	"Food": 300,
	"OtherExpenses": [50, 100],
	"Email": "user@test.com",
	"Phone": "010"
}

###

PATCH http://localhost:5000/api/user/myinformation
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1laWRlbnRpZmllciI6IjY3ZjhlYzJmMDE2MzA0ZTJiOTNjOGY2MyIsImV4cCI6MTc0NDkzMzY3NCwiaXNzIjoiQnVkZ2V0YXBwIiwiYXVkIjoiQnVkZ2V0YXBwVXNlcnMifQ.AId2URB2-TuhmqOuiVrIH174jJKy6b45LM5Dq7UQ5PQ
{
	"Firstname": "test",
	"Lastname": "user"
}

###
DELETE http://localhost:5000/api/user/myinformation
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1laWRlbnRpZmllciI6IjY3ZjhlYzJmMDE2MzA0ZTJiOTNjOGY2MyIsImV4cCI6MTc0NDkzNTYwNCwiaXNzIjoiQnVkZ2V0YXBwIiwiYXVkIjoiQnVkZ2V0YXBwVXNlcnMifQ.u0zHWgdnnIapUoS0uxtn1PUX3GFxHoPqgiiMThjBauQ
